### ISSUE TITLE
502 bad gateway error?

### ISSUE THREAD

**Issue by JoshuaCrotts** [YtoTech/latex-on-http#16]
I'm trying to use this API in my application, and it's all of the sudden giving me a 502 bad gateway error when I connect to it. Amazing API btw - hopefully this fixed soon.

**Comment by JoshuaCrotts** [comment]
Looks like it's back up.

**Comment by MonsieurV** [comment]
@JoshuaCrotts sorry, I didn't get a mail notification for this one.

Yeah, I was doing quite a lot of migrations on this server, that has provoked several down times.
Don't hesitate to reach at my email if there are any other issue. (Also if you'll require specific SLA)
