### ISSUE TITLE
Error : docker pull yoant/latexonhttp-python

### ISSUE THREAD

**Issue by thibault-chausson** [YtoTech/latex-on-http#21]
Hello,

I have a little problem with your Docker image. See the following screenshot.

![image](https://user-images.githubusercontent.com/82728820/200868365-a9fead46-8ea1-4525-894d-e303844e4320.png)

Thank you for your anwsers.

**Comment by MonsieurV** [comment]
Hi @thibault-chausson,

This is not an image published to the Docker hub. You must build it locally.
The simpler is to launch the Makefile entry `docker-build-all`. It will pull two remote images from docker.io, and build the others for LaTeX-on-HTTP locally.

**Comment by MonsieurV** [comment]
My bad, these images exist in docker.io, but not with the tag latest.

https://hub.docker.com/r/yoant/latexonhttp-python

Anyway the simpler is so start from the base [`Dockerfile`](https://github.com/YtoTech/latex-on-http/blob/master/Dockerfile#L15) (or better the [`docker-compose.yml`](https://github.com/YtoTech/latex-on-http/blob/master/docker-compose.yml)), which points to the right images.

**Comment by thibault-chausson** [comment]
It's good, everything is working
