### ISSUE TITLE
Update LaTeX compiler

### ISSUE THREAD

**Issue by thibault-chausson** [YtoTech/latex-on-http#22]
Hello,

Your solution works perfectly.

I have one last question, can I easily update the LaTeX compiler?

Thanks for your help,

Thibault

**Comment by MonsieurV** [comment]
Hi @thibault-chausson,

The base image used is https://github.com/YtoTech/docker-texlive, which contains a 2022 TexLive distribution.

You can rebuild it following your needs and then points to your own base image [here](https://github.com/YtoTech/latex-on-http/blob/master/container/tl-distrib-debian.Dockerfile#L15). Then you must rebuild locally all the LaTeX-on-HTTP images, the `make docker-build-all` is the simpler, even if it will includes a superfluous git pull)
