### ISSUE TITLE
Nginx 502 Bad Gateway

### ISSUE THREAD

**Issue by sy-filis** [YtoTech/latex-on-http#27]
When making request to load anything from https://latex.ytotech.com/, HTTP status code 502 with Bad Gateway is served back.

![image](https://github.com/YtoTech/latex-on-http/assets/130696213/ac5d6fd4-0edd-4cc6-b703-fba21cabe56e)

**Comment by MonsieurV** [comment]
Oh, I forget it after a server migration. It is up again. Thanks for the report @sy-filis.
